config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show, :index]
  get 'users/show'
  patch '/users/:id', to: 'users#update'
  get 'users/update'
  post '/points', to: 'points#create'
  get 'events/:id/rsvp', to: 'events#rsvp', as: :rsvp
  post 'events/:id', to: 'events#destroy'
  root 'events#index'
  # get 'event#new'
  resources :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :user_events
  has_many :users, through: :user_events
  has_many :points
  belongs_to :host, :foreign_key => :host_id, :class_name => 'User'
  validates :title, :location, :description, presence: true
  validates :title, length: { maximum: 30, too_long: "%{count} characters is the maximum allowed"}
  validates :description, length: { minimum: 30 }
  validates :location, length: { maximum: 30, too_long: "%{count} characters is the maximum allowed"}

  def point_givers
    array = []
    self.points.each do |point|
      array << point.sender.name
    end
    new_array = array.uniq
    new_array
  end

  def attendees
    array = []
    self.users.each do |user|
      array <<  user.name
    end
      new_array = array.uniq
      new_array
  end
  
end

app/models/organization.rb
class Organization
  include OrganizationsHelper
  include Change::Resources
  attr_accessor :client, :organization, :loaded_organization, :name, :website, :change_org_url

  def initialize
    @client = Change::Requests::Client.new({ :api_key => ENV["CHANGE_KEY"], :secret_token => ENV["CHANGE_SECRET"] })
    @organization = Organization.new(@client)
    @loaded_organization = @organization.load(pick_organization)
    @name = @loaded_petition['name']
    @website = @loaded_petition['website'] 
    @change_org_url = @loaded_petition['organization_url']
  end

  def pick_organization
    @organization_url = return_organizations_array.sample
  end
end

app/models/petition.rb
class Petition
  include PetitionsHelper
  include Change::Resources
  attr_accessor :client, :petition, :loaded_petition, :title, :creator_name

  def initialize
    @client = Change::Requests::Client.new({ :api_key => ENV["CHANGE_KEY"], :secret_token => ENV["CHANGE_SECRET"] })
    @petition = Petition.new(@client)
    @loaded_petition = @petition.load(random_petition_url)
    @title = @loaded_petition['title']
    @creator_name = @loaded_petition['targets'][0]['name']
  end

  def random_petition_url
    @random_url = return_petitions_array.sample
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  belongs_to :sender, :foreign_key => :sender_id, :class_name => 'User'
  belongs_to :receiver, :foreign_key => :receiver_id, :class_name => 'User'
  validate :sender_must_have_giveable_karma

  def sender_must_have_giveable_karma
    if self.sender.giveable_karma == 0
      errors.add(:sender, "must have karma to give")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_events
  has_many :events, through: :user_events
  has_many :points, foreign_key: :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader
  after_create :add_karma

  def add_karma
    self.giveable_karma = 10
    self.save
  end

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @dated_events = @events.sort_by &:date
    @points = Point.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new
    @event.date = params[:date]["date(3i)"] + "/" + params[:date]["date(2i)"] + "/" + params[:date]["date(1i)"] + "at" + params[:date]["date(4i)"] + ":" + params[:date]["date(5i)"]
    @event.title = params["title"]
    @event.location = params["location"]
    @event.description = params["description"]
    @event.host = User.find(params["host_id"])
    @event.users << current_user
    unless @event.save
      render 'error.js'
    end
  end

  def rsvp
    @event = Event.find(params["id"])
    @event.users << current_user
    @event.save
    current_user.save
  end

  def show
    @event = Event.find(params["id"])
  end

  def destroy
    @event = Event.find(params["event_id"])
    @event.destroy
    redirect_to root_url
  end

private

  def event_params
      params.require(:event).permit(:title, :location, :description)
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def new
    @point = Point.new
  end

  def create
    @point = Point.new
    @point.value = 1
    @point.receiver = User.find(params["receiver_id"])
    @event = Event.find(params["events"]["id"])
    @point.sender = User.find(params["sender_id"])
    @user = User.find(params["receiver_id"])
    karma_increment
    @event.points << @point
    @point.save
    @points_received = Point.where(receiver_id: params["receiver_id"])
  end

  def show
  end

  def index
    @point = Point.all
  end

  def karma_increment
    @user.giveable_karma += 2
    @user.save
    @point.sender.giveable_karma -= 1
    @point.sender.save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @id = params[:id]
    @user = User.find_by_id(@id)
    @points_received = Point.where(receiver_id: @id)
  end

  def index
    @users = User.all
  end

  def update
    new_update = UserUpdateService.new(params, current_user)
    if params[:user][:image] != nil
      new_update.update_image
      redirect_to :back
    end 
    new_update.update_name
    new_update.update_location
    new_update.update_mission
    @name = current_user.name
    @location = current_user.location
    @mission = current_user.bio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def return_organizations_array
    @organization_array = [
      "https://www.change.org/organizations/goodli"
    ]
  end
end

app/helpers/petitions_helper.rb
module PetitionsHelper
  def return_petitions_array
    @petition_array = [
      "https://www.change.org/p/george-toothman-safe-immigration",
      "https://www.change.org/p/george-toothman-fare-wages",
      "https://www.change.org/p/george-toothman-bike-lanes"
    ]
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def unique_point(points_array)
    # iterate over that array and do all the fancy stuff from the view
  end
end

app/views/event/index.html.erb
<% if user_signed_in? %>
  <%= link_to "Profile", controller: "users", action: "show", id: current_user.id %>
<% end %>

<h1> Homepage </h1>
<h1>IMAGE GOES HERE</h1>
<h2>List of Events</h2>
<h2>Event creation form</h2>
<h2>Karma point index</h2>

app/views/events/_create.html.erb
    <%= form_tag('/events', method: 'post', remote: true) do %>
    <p>
      <%= label_tag("Event Title") %>
    </p>
      <%= text_field_tag :title %>
    </p>
    <p>
      <%= label_tag("Location") %>
    </p>
    <p>
      <%= text_field_tag :location %>
    </p>
    <p>
      <%= label_tag("Description") %>
    </p>
    <p>
      <%= text_area_tag :description %>
    </p>
      <%= hidden_field_tag :host_id, current_user.id %>
    <p>
      <%= datetime_select "date", :date, ampm: true %>
    </p>
    <p>
      <%= submit_tag('Submit') %>
    </p>
<% end %>

app/views/events/_errors.html.erb
<div class='alert alert-danger' role='alert'>
  <% if @event.errors.messages[:title] != nil %>
    <p>Your title <%= @event.errors.messages[:title][0] %></p>
  <% end %>
  <% if @event.errors.messages[:location] != nil %>
    <p>Your location <%= @event.errors.messages[:location][0] %></p>
  <% end %>
  <% if @event.errors.messages[:description] != nil %>
    <p>Your description <%= @event.errors.messages[:description][0] %></p>
  <% end %>
</div>

app/views/events/_event.html.erb
<center>
<h3><%= link_to @event.title, controller: "events", action: "show", id: @event.id %></h3>
    <h4>Creator: <%= link_to @event.host.name, controller: "users", action: "show", id: @event.host.id %></h4>
    <h4>Location: <%= @event.location %></h4>
    <h4>Date: <%= @event.date.in_time_zone("EST").to_formatted_s(:short) %> (EST) </h4>
</center>

app/views/events/create.js.erb
$(".new_event").append("<%= j render(:partial => 'events/event') %>");
var y = $(window).scrollTop();  //your current y position on the page
$(window).scrollTop(y-300);
$("#event_errors").html("<div class='alert alert-success' role='alert'>Your event has been created</div>")

app/views/events/error.js.erb
$("#event_errors").html("<%= j render(:partial => 'events/errors') %>")

app/views/events/index.html.erb
<header class="intro">

    <!-- Video from YouTube. Have Questions? How To: https://github.com/pupunzi/jquery.mb.YTPlayer/wiki -->
    <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=TYrX7w1uIq8', containment:'body', autoPlay:true, realfullscreen:true, optimizeDisplay:true, loop:true, mute:true, startAt:0, stopAt: 200, quality:'auto', opacity:1, showControls: false, showYTLogo:false, vol:25}"></a>

    <div class="intro-body">
        <!-- <img src="img/logo.png" alt="" class="wow fadeIn" data-wow-duration="4s" data-wow-delay=".4s"> -->
        <div id="clock" class="wow fadeIn" data-wow-duration="6s" data-wow-delay=".6s"></div>
        <p class="intro-text wow fadeIn" data-wow-duration="7s" data-wow-delay=".7s"><h1><%= image_tag "glogo.png", size: "600"%></h1></p>

    </div>

    <div class="video-controls">
        <a id="video-volume" class="fa fa-volume-off fa-lg" href="#"></a>
        <a id="video-play" class="fa fa-pause fa-lg" href="#"></a>
    </div>
</header>


<!-- Action2 Section -->
<section class="action2 container-fluid wow fadeIn">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div style="background:transparent !important" class="jumbotron">
            <div class="new_event">
              <center><h1>Upcoming Events</h1></center>
              <br></br>
              <center>
              <% @dated_events.each do |event| %>
                <% if event.date > Time.now %>
                  <h3><%= link_to event.title, controller: "events", action: "show", id: event.id %></h3>

                    <h4>Creator: <%= link_to event.host.name, controller: "users", action: "show", id: event.host.id %></h4>
                    <h4>Location: <%= event.location %></h4>
                    <h4>Date: <%= event.date.in_time_zone("EST").to_formatted_s(:short) %> (EST)</h4>
                  </br>
                <% end %>
              <% end %>
            </center>
            </div>
          </div>
        </div>
    </div>
</section>

<!-- About Section -->
<section id="about" class="container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <% if user_signed_in? %>
          <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Create an Event</h2>
          </div>
          <div style="background:transparent !important" class="panel-body" id="event_creator">
            <%= render 'create' %>
          <div id="event_errors">
          </div>
          </div>
        </div>
        <% else %>
          <h2>Log In to Create an Event!</h2>
        <% end %>
        </div>
    </div>
</section>

<!-- About2 Section -->
<section id="about2" class="container-fluid text-center wow fadeIn">
    <div class="col-lg-10 col-lg-offset-1">
        <h1>Karma Exchanged to Date: <%= @points.length %></h1>
    </div>
</section>

<!-- Action2 Section -->
<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">

            <h4>GOODli is the premier social impact social network. Create and attend meaningful events, build your karma, and connect with users across the globe to advance your social impact mission. Find the code and an overview <a href="https://github.com/ehawk823/Goodli2">here</a>.</h4>


        </div>
    </div>
</section>

app/views/events/rsvp.js.erb
$("#new_attendee").prepend("<%=current_user.name%>, ")
$(".rsvp_button").hide()

app/views/events/show.html.erb
<section class="action2 container-fluid wow fadeIn">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div style="background:transparent !important" class="jumbotron">
        <h3><%= @event.title %></h3>
        <ul>
          <h4><li>Description: <%= @event.description %> </li></h4>
          <h4><li>Creator: <%= link_to @event.host.name, controller: "users", action: "show", id: @event.host.id %></li></h4>
          <h4><li>Location: <%= @event.location %></li></h4>
          <h4><li>Date: <%= @event.date.in_time_zone("EST").to_formatted_s(:short) %> (EST) </li></h4>
          <h4><li>Attendees:
            <div id="new_attendee">
              <% @event.attendees.each do |name| %>
                <%= name %>,
              <% end %>
              <% if @event.attendees.length == 0 %>
                Nobody yet!
              <% else %>
                and more to come!
              <% end %>
              </div>
          </li></h4></ul>
          <div class="rsvp_button">
          <% if user_signed_in? %>
            <% if @event.users.include?(current_user) == false %>
              <font color="black"><%= link_to "RSVP", rsvp_path(@event), remote: true %></font>
            <% end %>
          </div>
            <% if current_user == @event.host %>
              <% if @event.points.length == 0 %>
                <font color="black"><%= button_to "Delete Event", :event_id => @event.id, controller: 'events', action: "destroy" %></font>
              <% end %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= link_to "Profile", controller: "users", action: "show" %>
<% end %>

<h1> Homepage </h1>

<h2>Trending Projects - Petitions, Kickstarter, etc.</h2>
<h2>List of Recent Karma Exchanges</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <script type="text/javascript" src="https://launcher.zo.la/assets/zbwidget-launcher-0.1.0.js"></script>
    <script type="text/javascript">
        zb.init({
            api_key: '',
            store_uid: 'EVANS',
            widget_launcher: 'https://launcher.zo.la'
        });
    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <style type="text/css">
     a:hover {
      cursor:pointer;
     }
    </style>
    <title>Goodli</title>

  <%= csrf_meta_tags %>


    <!-- Custom fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>

    <!-- Background Slider -->
    <!-- Custom CSS -->
<!--     <link href="css/csoon.css" rel="stylesheet">
 -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<%# yield %>
<!-- Preloader -->
<div id="preloader"><div id="status">&nbsp;</div></div>

<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top wow fadeIn" data-wow-duration="3s" data-wow-delay=".2s" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars fa-2x"></i>
            </button>
            <a class="navbar-brand page-scroll wow fadeInRight" data-wow-duration="1s" data-wow-delay="1.4s" href="#page-top">
                <span class="logo">GOODli</span> <i class="fa fa-star"></i>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1.4s">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="active"><%= link_to "Home", events_path %></li>
                <li class="active"><a data-zb-launch="info" data-isbn="9781462916788">Everywhere Store</a></li>
                <% if user_signed_in? %>
                <li class="active"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %><span class="sr-only">(current)</li>
                <li class="active"><%= link_to "Profile", controller: "users", action: "show", id: current_user.id %><span class="sr-only">(current)</li>
                <% else %>
                <li class="active"><%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="active"><%= link_to "Login", new_user_session_path %></li>
                <% end %>
                <li class="active"><%= link_to "Users", users_path %></li>
            </ul>
        </div>
    </div>
</nav>

<%= yield %>


<!-- jQuery -->

<!-- Bootstrap Core JavaScript -->
<%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

<!-- Plugin JavaScript -->

<!-- Google Map -->
<!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->

<!-- Plugins for video background -->

<!-- Custom Theme JavaScript -->

</body>
</html>

app/views/points/_mevent.html.erb
<h3><%= @event.title %></h3>
<blockquote>
<h4>Karma: <%= @event.points.length %></h4>
<% array = [] %>
<h4>From:
      <% @event.points.each do |point| %>
      <%array << point.sender.name %>
      <% end %>
      <% new_array = array.uniq %>
      <% new_array.each do |name| %>
        <%= name %>,
      <% end %>
      <% if @event.points.length == 0 %>
        hmmm looks like nobody
      <% else %>
        and the universe!
      <% end %>
      </h4>
</blockquote>

app/views/points/create.js.erb
$('#total_karma_uptick').html('<%= @points_received.length %>')
$('#<%=@event.id%>').html("<%= j render(:partial => 'points/mevent') %>")
var y = $(window).scrollTop();  //your current y position on the page
$(window).scrollTop(y-300);
$('#giveable_karma').html('<h2>You have <%= current_user.giveable_karma %> Karma left to give away.</h2>')
$('#give_karma').html("<%= j render(:partial => 'users/points') %>")

app/views/users/_points.html.erb
<% if current_user.giveable_karma > 0 %>
<div class="alert alert-info" role="alert">
<%= form_tag('/points', method: 'post', remote: true) do %>
  <%= label_tag("Please select an event to award a karma point") %>
  <%= hidden_field_tag :receiver_id, @user.id %>
  <%= hidden_field_tag :sender_id, current_user.id %>
  <%= collection_select :events, :id, @user.events, :id, :title %>
  <%= submit_tag('Submit') %>
</div>
<% end %>
<% else %>
  <div class="alert alert-danger" role="alert">
    "You have no more giveable karma"
  </div>
<% end %>

app/views/users/_user.html.erb
<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div style="background:transparent !important" class="jumbotron">
            <h1>
              <div id = "image_input">
                <% if current_user.image.model[:image] == nil %>
                  <%= image_tag "icon-user-default.png", size: "200"%>
                <% else %>
                  <%= image_tag current_user.image.to_s, size: "200"%>
                <% end %>
              </div>
            </h1>
            <%= form_for current_user, :html => {:multipart => true}, remote: true do |f| %>
                <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
                  <font color="black"><%= f.submit "Update Image" %></font>
                  <center><%= f.file_field :image %></center>
            <% end %>
          </div>
        </div>
    </div>
</section>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <div id = "name_input">
        Name: <%= current_user.name %>
      </div>
      </h3>
      <div id = "name_form">
        <%= form_for current_user, remote: true do |f|  %>
          <%= f.text_field :name %>
          <%= f.submit 'Update Name'%>
        <% end %>
      </div>
      <button id = "edit">Edit</button>
  </div>
  <div class="panel-body">
    Location:
    <div id = "location_input">
      <%= current_user.location %>
    </div>
    <div id = "location_form">
      <%= form_for current_user, remote: true do |f|  %>
        <%= f.text_field :location %>
        <%= f.submit 'Update Location'%>
      <% end %>
    </div>
    <button id = "edit_location">Edit</button>
    <br></br>
    Social Impact Mission:
    <div id = "mission_input">
      <%= current_user.bio %>
    </div>
    <div id = "mission_form">
      <%= form_for current_user, remote: true do |f|  %>
        <%= f.text_field :bio %>
        <%= f.submit 'Update Mission Statement'%>
      <% end %>
    </div>
    <button id = "edit_mission">Edit</button>
  </div>
</div>

<div class="well">
<h3>Karma Received: <%= @points_received.length %></h3>
</div>

<div class="jumbotron">
<h2>Your Recent Events</h2>
  <% current_user.events.each do |event| %>
<h3>Event: <%= event.title %></h3>
<blockquote>
<h4>Karma: <%= event.points.length %></h4>
  <% array = [] %>
<h4>From: <% event.points.each do |point| %>
        <%array << point.sender.name %>
        <% end %>
        <% new_array = array.uniq %>
        <% new_array.each do |name| %>
          <%= name %>,
        <% end %>
        <% if event.points.length == 0 %>
          hmmm looks like nobody
        <% else %>
          and the universe!
        <% end %>
        </h4>
</blockquote>
<% end %> </h4>
</blockquote>
</div>

<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <!-- MailChimp Signup Form -->
            <!-- Replace the form action in the line below with your MailChimp embed action! For more informatin on how to do this please visit the Docs! -->
            <h2>Thank you for coming to Goodli</h2>
            <!-- End MailChimp Signup Form -->
        </div>
    </div>
</section>

app/views/users/_visitor.html.erb
<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div style="background:transparent !important" class="jumbotron">
            <div id = "image_input">
              <% if @user.image.model[:image] == nil %>
                <%= image_tag "icon-user-default.png", size: "200"%>
              <% else %>
                <%= image_tag @user.image.to_s, size: "200"%>
              <% end %>
            </div>
          </div>
        </div>
    </div>
</section>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      Name: <%= @user.name %>
    </h3>
  </div>
  <div class="panel-body">
    Location: <%= @user.location %>
    <br></br>
    Mission: <%= @user.bio %>
  </div>
</div>
<br></br>
<h2>User's recent events</h2>
<div class="jumbotron">
<blockquote>
<% @user.events.each do |event| %>
  <div id='<%= event.id %>'>
    <h3><%= event.title %></h3>
  <blockquote>
  <h4>Karma: <%= event.points.length %></h4>
    <% array = [] %>
  <h4>From:
          <% event.point_givers.each do |name| %>
            <%= name %>,
          <% end %>
          <% if event.points.length == 0 %>
            hmmm looks like nobody
          <% else %>
            and the universe!
          <% end %>
          </h4>
  </blockquote>
</div>
<% end %> </h4>
</blockquote>
</div>

<% if user_signed_in? %>
  <h2>Give <%=@user.name%> Karma for something awesome they've done!</h2>
  <div id='giveable_karma'><h2>You have <%= current_user.giveable_karma %> Karma left to give away.</h2></div>
  <div id='give_karma'>
    <%= render 'points' %>
  </div>
<% end %>

<h2>Karma <%= @user.name%> has received: <div id="total_karma_uptick"><%= @points_received.length %></h2></div>

<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <!-- MailChimp Signup Form -->
            <!-- Replace the form action in the line below with your MailChimp embed action! For more informatin on how to do this please visit the Docs! -->
            <h2>Thank You for Coming to Goodli</h2>
            <!-- End MailChimp Signup Form -->
        </div>
    </div>
</section>

app/views/users/index.html.erb
<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div style="background:transparent !important" class="jumbotron">
            <h1>
              <h1>Goodli Users</h1>
            </h1>
          </div>
        </div>
    </div>
</section>

<section id="services" class="container-fluid text-center wow fadeIn">
    <div class="col-lg-12">
        <div class="row">
          <% @users.each do |user| %>
            <div class="col-lg-3 col-sm-6 wow fadeIn" data-wow-delay=".2s">
                <h4>
                  <% if user.image.model[:image] == nil %>
                    <%= image_tag "icon-user-default.png", size: "150"%>
                  <% else %>
                    <%= image_tag user.image.to_s, size: "150"%>
                  <% end %>
                   <p><%= link_to user.name, controller: "users", action: "show", id: user.id %></p></h4>
                <p>Karma Received: <%= Point.where(receiver_id: user.id).length %></p>
            </div>
          <% end %>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <% if current_user.id == @id.to_i %>
    <%= render partial: "user" %>
  <% else %>
    <%= render partial: "visitor" %>
  <% end %>
<% else %>
  <%= render partial: "visitor" %>
<% end %>

app/views/users/update.js.erb
$("#name_form").hide();
$("#name_input").show();
$("#name_input").html("<%=@name%>")
$("#edit").show();

$("#location_form").hide();
$("#location_input").show();
$("#location_input").html("<%=@location%>")
$("#edit_location").show();

$("#mission_form").hide();
$("#mission_input").show();
$("#mission_input").html("<%=@mission%>")
$("#edit_mission").show();

// $("#image_input").html("<%= image_tag @image %>")